# .github/workflows/ci.yml
name: CI for JS Testing
# Trigger the workflow on pull requests to the main branch
on:
pull_request:
branches:
- main
jobs:
test:
runs-on: ubuntu-latest
steps:
- name: Checkout repository code
uses: actions/checkout@v3
- name: Set up Node.js
uses: actions/setup-node@v3
with:
node-version: '18' # Specify the Node.js version
- name: Install dependencies
run: npm install
- name: Run tests
run: npm test
