name: CI for JS Testing
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version: ['16', '18', '20']
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        if: ${{ !startsWith(matrix.node-version, '16') }}
        run: npm test

      - name: Run tests (single-thread for Node 16)
        if: ${{ startsWith(matrix.node-version, '16') }}
        run: npm test -- --runInBand
        
      - name: Run ESLint (Node >=18)
        if: ${{ matrix.node-version >= 18 }}
        run: npm run lint

  build:
    name: Build react app after tests
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build react app
        run: npm run build

      - name: Run react app tests
        working-directory: ./test-app
        run: npm test
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
          artifact_name: site-artifact

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.node-version == 18 }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: site-artifact
    
