name: CI for JS Testing
# Trigger the workflow on pull requests to the main branch
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version: ['17', '18', '20']
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        if: ${{ !startsWith(matrix.node-version, '16') }}
        run: npm test

      - name: Run tests (single-thread for Node 16)
        if: ${{ startsWith(matrix.node-version, '16') }}
        run: npm test -- --runInBand
        
      - name: Run ESLint
        run: npm run lint
