name: my first workflow
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: List files in repo
        run: |
          echo "repo ${{ github.repository }} contains following files:"
          tree
